### ISSUE TITLE
Typo @ https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-about-virtual-server

### ISSUE THREAD

**Issue by douglin** [ibm-cloud-docs/power-iaas#10]
"Serer" should be "server" in the note "For a complete list of supported data centers, see Creating a Power Systems Virtual Serer service."
<img width="651" alt="Screen Shot 2021-03-25 at 10 29 26 AM" src="https://user-images.githubusercontent.com/6821196/112489626-ff01a800-8d54-11eb-97b2-f30e9f27fb14.png">

**Comment by mpudota907** [comment]
@douglin thank you for feedback. Corrected typo error.
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-about-virtual-server
