### ISSUE TITLE
URL of AIX software map

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/power-iaas#10]
Hello,

About this page:
https://cloud.ibm.com/docs/infrastructure/power-iaas?topic=power-iaas-deploy-custom-image&locale=en#before-you-begin-deploy

Currently, the URL for All I/O Configurations is written as a AIX software map, but since Power Virtual Servers on IBM Cloud run in VIOS environment, I think that the URL for VIOS is correct.
Could you please check that?

[ Current URL ]
S922: https://www-01.ibm.com/support/docview.wss?uid=ssm1platformaix9009-22A-all-io
E880: https://www-01.ibm.com/support/docview.wss?uid=ssm1platformaix9119-MHE-all-io

[ URL that I think correct ]
S922: https://www-01.ibm.com/support/docview.wss?uid=ssm1platformaix9009-22A-vios-only
E880: https://www-01.ibm.com/support/docview.wss?uid=ssm1platformaix9119-MHE-vios-only

Thanks,

**Comment by mpbagwel** [comment]
@ytama Sounds good. I updated the AIX software maps for both systems to be VIOS-only. You'll see the update out on production in about 30 minutes. Thanks!

https://cloud.ibm.com/docs/infrastructure/power-iaas?topic=power-iaas-power-iaas-faqs
