### ISSUE TITLE
s1022 is not available only in Dallas, it is also in Madrid

### ISSUE THREAD

**Issue by Alejandrodelgado** [ibm-cloud-docs/power-iaas#100]

**Comment by Alejandrodelgado** [comment]
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-pricing-virtual-server

**Comment by Itsmemukesh** [comment]
Made changes in the pricing docs to reflect: 
> Power System S1022 is available only in DAL10, MAD02, MAD04, and WDC07.

https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-pricing-virtual-server
