### ISSUE TITLE
Power Virtual Server: Hyperlink from public cloud docs restricted to 'authorized' users - needs correction

### ISSUE THREAD

**Issue by sealbou** [ibm-cloud-docs/power-iaas#101]
This page has a link that is only for 'authorized' users: 

https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-use-case-oracle

The hyperlink in this section: 
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-use-case-oracle#building-oracle

**Comment by sealbou** [comment]
Additionally the first link on this page is also only for "authorized" users so this page is essentially useless @Itsmemukesh if you can please address I'd appreciate it

**Comment by Itsmemukesh** [comment]
The issue is being discussed with the Oracle SPOCS - Doug Bloom & Steve Huntington.
Susan to provide updates on the changes required for docs.

**Comment by Itsmemukesh** [comment]
revised the topic with apt content.
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-use-case-oracle
