### ISSUE TITLE
The hourly rate appears to be incorrect.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/power-iaas#102]
Hello,
In this table, the hourly rate is higher for S922 than for S1022, but the monthly cost is higher for S1022.
I think the hourly rate of S922 is not correct. Could you please check this?
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-pricing-virtual-server
![pricing_pvs](https://github.com/ibm-cloud-docs/power-iaas/assets/9413593/6bf1522f-9c0f-453d-97f9-50939efb5761)

**Comment by Itsmemukesh** [comment]
https://test.cloud.ibm.com/docs/power-iaas?topic=power-iaas-pricing-virtual-server#pricing-processor
Changes made on the table 4 & 5.
@ytama

**Comment by Itsmemukesh** [comment]
Changes in production now: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-pricing-virtual-server#pricing-processor
