### ISSUE TITLE
Migrating toi Power Edge Router document - step 6 should link to Direct Link instructions

### ISSUE THREAD

**Issue by bmlandman** [ibm-cloud-docs/power-iaas#103]
On [the page for Migrating to Power Edge Router ](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-migrate-ws-per)- there are instructions for end users to follow in order to move their workspace to PER. Step 6 in that list, should link to the page where there are instructions on how to delete a Direct Link connection. 

Step 6: Upon successful testing, delete the Direct Link connections and notify IBM by updating the ticket.

Link to page with instructions for deleting a Direct Link and it's attached connections: [](https://cloud.ibm.com/docs/dl?topic=dl-delete-direct-link-gateway&interface=ui)

Also it would be helpful to know what detail needs to be added to the ticket.

**Comment by Itsmemukesh** [comment]
Step 6 is now hyperlinked.
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-migrate-ws-per
