### ISSUE TITLE
Missing region in list for "PowerVS Importing Boot Image" instructions

### ISSUE THREAD

**Issue by mhren** [ibm-cloud-docs/power-iaas#104]
The list of regions on this page (https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-importing-boot-image) should also include eu-es.

`Select either us-east, us-south, ca-tor, eu-de, or eu-gb, au-syd, jp-tok, jp-osa for the region.` should be 
`Select either us-east, us-south, ca-tor, eu-de, eu-es, eu-gb, au-syd, jp-tok, or jp-osa for the region.`

**Comment by Itsmemukesh** [comment]
Topic revised.
