### ISSUE TITLE
Duplicate step in "Before You Begin" section of doc

### ISSUE THREAD

**Issue by slaphen** [ibm-cloud-docs/power-iaas#105]
At link: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-getting-started

Step 4 "Create a public and private SSH key that you can use to securely connect to your Power Virtual Server. To create a public and private SSH key, see [Adding an SSH key](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-ssh-key)."  appears to be a duplicate of the prior Step 3.

**Comment by Itsmemukesh** [comment]
Removed duplicate step and the SSH content has now moved to : https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-ssh-key
