### ISSUE TITLE
Please remove "external ip" from pcloud-pvminstances-getall-response as it's no longer returned 

### ISSUE THREAD

**Issue by sammagnum** [ibm-cloud-docs/power-iaas#106]
https://cloud.ibm.com/apidocs/power-cloud#pcloud-pvminstances-getall-response
Please reach out to @samm in Infrastructure slack workspace with any questions

Sam Mangum
sjmangum@us.ibm.com

**Comment by Itsmemukesh** [comment]
@sammagnum 
Can you post the response that you are getting?

**Comment by Itsmemukesh** [comment]
This issue is tracked from the JIRA - https://jsw.ibm.com/browse/POWERIAAS-11641

**Comment by Itsmemukesh** [comment]
Closing this issue, as the parent issue got cancelled.
