### ISSUE TITLE
Doc on limits seems unneccesary 

### ISSUE THREAD

**Issue by andrewlow** [ibm-cloud-docs/power-iaas#107]
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-monitor-sysdig#sysdig-limits

This feels like someone took the doc for enabling platform metrics - and translated it to customer facing.. when the limits are instructive for the IBM service team implementing platform metrics, but not useful (or relevant) to a customer.

**Comment by Itsmemukesh** [comment]
@andrewlow 
Please provide a list of potential sections that you think should be useful (or relevant) to a customer.

**Comment by andrewlow** [comment]
Some of the content seems weird to me. I don't understand why it's present

> When you exceed the predefined limits, the rate-limited requests respond with a 503 Service Unavailable error.

Why or how would a customer get a 503 with this function?

> IBM Cloud Monitoring accepts data within a specific time range that is called the window of acceptance that is fixed to 5 minutes.

Again, this is a limitation for the sending service - not for the customer.

**Comment by Itsmemukesh** [comment]
Removed the 2 limitations.
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-monitor-sysdig#sysdig-limits
