### ISSUE TITLE
DCs Missing in PER Table

### ISSUE THREAD

**Issue by surajsbharadwaj** [ibm-cloud-docs/power-iaas#108]
There are total of 21 DCs for PowerVS.
The table shows only 19 Dc instead of 21.

Please add missing DCs to the table.
1. Mon01
2. Us-east(wdc04)

**Comment by Itsmemukesh** [comment]
PER DCs were updated.
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-per#dcs-per
