### ISSUE TITLE
Capturing and Exporting LPAR Image - CLI Commands Outdated

### ISSUE THREAD

**Issue by heyfrancisco** [ibm-cloud-docs/power-iaas#109]
Hi team,

The CLI Commands presented here https://cloud.ibm.com/docs/power-iaas-cli-plugin?topic=power-iaas-cli-plugin-power-iaas-cli-reference-v1#ibmcloud-pi-image are outdated.

Please update the documentation with the new PowerVS CLI V1.1 commands https://cloud.ibm.com/docs/power-iaas-cli-plugin?topic=power-iaas-cli-plugin-power-iaas-cli-reference-v1#ibmcloud-pi-instance-capture-create.

Thanks,
Francisco Ramos do Ó

**Comment by Itsmemukesh** [comment]
Hello!,
The new CLI commands v1.2.0 are available.
https://cloud.ibm.com/docs/power-iaas-cli-plugin?topic=power-iaas-cli-plugin-power-iaas-cli-reference-v1
