### ISSUE TITLE
Shouldn’t it say “no longer supported by Red Hat.“?

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/power-iaas#110]
Hello,
Regarding this release note, I don’t think RHEL support has anything to do with SUSE. Shouldn’t it say “no longer supported by Red Hat.“?
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-release-notes#jun-2024

> The RHEL 8.6 general purpose (RHEL8-SP6) stock image is in the process of being removed from our data center since the OS is level no longer supported by SUSE.

**Comment by Itsmemukesh** [comment]
Agreed.
changes made
