### ISSUE TITLE
Pricing is out of date

### ISSUE THREAD

**Issue by mraquinn** [ibm-cloud-docs/power-iaas#111]
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-pricing-virtual-server-on-cloud#per-pricing

Links shows: Local routing data transfer	No charges

This is not the case when using the estimator.

**Comment by Itsmemukesh** [comment]
Removed link to cost estimator as it does not show any details for PER and might lead to confusion. Added the string "See the summary of Transit Gateway charges from the [provisioning page](https://cloud.ibm.com/interconnectivity/transit/provision) in the IBM Cloud console. See the [Pricing considerations](https://cloud.ibm.com/docs/transit-gateway?topic=transit-gateway-helpful-tips#pricing-considerations) section in the Transit Gateway documentation for more information."
