### ISSUE TITLE
Confusing section

### ISSUE THREAD

**Issue by mraquinn** [ibm-cloud-docs/power-iaas#112]
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-pricing-virtual-server-on-cloud#per-pricing

Title is "Pricing for PER", first sentence is "PER is not charged for" followed by pricing for Transit Gateway (which isn't show on the Transit Gateway Docs pages. The Cost Estimator link leads to the page for Power VS, not Transit Gateway.

**Comment by Itsmemukesh** [comment]
The charges for Transit Gateway-based routing are listed correctly. Why should the Cost Estimator link lead to Transit gateway docs? It is linked to the cost estimator tool to perform hit/trial and see the corresponding changes before provisioning them.
