### ISSUE TITLE
Migration strategies for IBM i

### ISSUE THREAD

**Issue by mlventer** [ibm-cloud-docs/power-iaas#114]
### Which topic are you reporting about?

On this page

https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-migration-strategies-power

There is a section that references an outdated document and needs to be removed (or updated with a new document)

For a complete tutorial on migrating your IBM i workloads to Power Virtual Servers, see [Migrating IBM i to IBM Power Virtual Servers](https://cloud.ibm.com/media/docs/downloads/power-iaas-tutorials/PowerVS_IBMi_Migration_Tutorial_v1.pdf).

### What do you think needs to be updated?

Reference to the doc needs to be removed

**Comment by Itsmemukesh** [comment]
Removed the reference to old lab services pdf with consensus from the engineering team.
