### ISSUE TITLE
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-ibmi-lpps

### ISSUE THREAD

**Issue by Axel-kyndryl** [ibm-cloud-docs/power-iaas#115]
### Which topic are you reporting about?

BRMS 5770-BR2 is missing on the document is it an addtionnal LPP? 

### What do you think needs to be updated?

include BRMS 5770-BR2

**Comment by Itsmemukesh** [comment]
Added 5770-BR2: Backup, Recovery, and Media Services. Changes will publish on September 23.
