### ISSUE TITLE
mistake in vpc prefixes

### ISSUE THREAD

**Issue by lluissabarich** [ibm-cloud-docs/power-iaas#116]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-VPN-connections#arch-per

### What do you think needs to be updated?

there is a mistake in the vpc prefixes since they are incorrect ... they should include 192.168. .... and remove the one from onprem

**Comment by Itsmemukesh** [comment]
This item has no details.  The VPN support should all be thru the VPC support, and that configuration used.  We are quickly approaching VPN end of support.
