### ISSUE TITLE
COLO via Megaport requires MCR

### ISSUE THREAD

**Issue by phoneline99** [ibm-cloud-docs/power-iaas#12]
In order for a customer to connect two POWER VS cloud services together, they have to use a MCR.  The only way to go directly between the services is if the offering provided that connection.  Please update the diagram(s) to reflect the MCR.

**Comment by mpbagwel** [comment]
Thanks for your feedback! I'll be working with my networking dev team to get additional diagrams in place.

**Comment by mpbagwel** [comment]
@phoneline99 We added more information regarding the use of an MCR above the [IBM Power colo to colo connection](https://cloud.ibm.com/docs/infrastructure/power-iaas?topic=power-iaas-network-reference-architecture#colo-to-colo) diagram. Let me know if there's anything else.

**Comment by mpbagwel** [comment]
**The issue has been resolved. If something was missed or more work is required, please reopen the issue.**
