### ISSUE TITLE
Information that docs indicates is not enough for establishing Direct Link Connect 2.0.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/power-iaas#13]
I'm referring this docs to establish Direct Link Connect 2.0
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-ordering-direct-link-connect&locale=en

On step 11, the docs says the following information is required to establish the connection. But when I opened a case, Power's support staff required additional information. Specifically, they asked me for a screen capture of the Direct Link settings and information on the VLAN number to which AIX belongs. If we know it from the beginning, we can efficiently create a case, so please describe this point in the docs.

-------------------
Customer name:
Customer account ID:
Data center details:
Direct Link Connect subnet:
IBM Cloud IP address:
Power Systems Virtual Server network IP address:
IBM Cloud ASN:
Power Systems Virtual Server network ASN:
Power Systems Virtual Server Private Network (subnet) Name (1):
Power Systems Virtual Server Private Network (subnet) Name (2):
Power Systems Virtual Server Private Network (subnet) Name (3):
-------------------

Thank you,

**Comment by mpudota907** [comment]
@ytama updated the doc. Please review and let me know if we need to add any more details
![image](https://user-images.githubusercontent.com/67143565/114363856-724d4b80-9b96-11eb-805a-6eacd8d451e4.png)

**Comment by prarredd** [comment]
@ytama : Please verify the updates so the issue can be closed.

**Comment by prarredd** [comment]
Assuming there are no more comments closing this issue.
