### ISSUE TITLE
What's "Private Network ID"?

### ISSUE THREAD

**Issue by khayama** [ibm-cloud-docs/power-iaas#13]
Please describe the detail of Private Network ID at the order process 13.
I don't understand what kind of information should be filled, thanks.

>Private Network ID (1):
>Private Network ID (2):
>Private Network ID (3):

**Comment by mpbagwel** [comment]
Hi @khayama, 

Are you asking about step 12 in the [Direct Link Connect for Power Systems Virtual Servers](https://test.cloud.ibm.com/docs/infrastructure/power-iaas?topic=power-iaas-ordering-direct-link-connect) page?

>12. Use the information from the Direct Link Connect case number to update the Power Systems Virtual Server support case:

>Link Speed:                  1000 Mbps
Location:                    Washington 2
Network Provider:            MEGAPORT
IBM IP Address:              10.254.0.25/30
Customer IP Address:         10.254.0.26/30
Service Key:                 None
BGP ASN:                     64999
Network Identifier:          1748523-1
Date Created:                2019-06-12T14:56:45-06:00

**Comment by khayama** [comment]
Yes, I can see it in step 13 ticket template.
What’s “Private Network ID” to be filled?

**Comment by mpbagwel** [comment]
@khayama I reached out to my networking team and they said that the Private Network ID is your subnet name. Here's an example:

Name: **ibm_net01**
Location: us-east
CIDR: 192.168.12.0/24
IP ranges: 192.168.12.4-192.168.12.254
DNS Servers: 127.0.0.1

Let me know if you have any other questions.

**Comment by khayama** [comment]
Thanks, I will issue the pull req refrecting this.

**Comment by khayama** [comment]
@mpbagwel Thanks, please let me know when you merged

**Comment by mpbagwel** [comment]
@khayama Take a look out here:

https://cloud.ibm.com/docs/infrastructure/power-iaas?topic=power-iaas-ordering-direct-link-connect

**Comment by khayama** [comment]
@mpbagwel Looks great! Thanks for clarifying.

**Comment by mpbagwel** [comment]
@khayama Not a problem. Thanks for taking the time to review the documentation. Feel free to open up issues on this repo as you think of them.
