### ISSUE TITLE
Missing encryption details for Power VS storage

### ISSUE THREAD

**Issue by kbroussard** [ibm-cloud-docs/power-iaas#14]
Critical security information such as encryption is missing from the Power VS cloud.ibm.com/docs.  Please add encryption details such as encrypted at rest by default, AES-256?, vendor managed keys, etc.  Thanks.

**Comment by prarredd** [comment]
@Mukesh: Please check with Ravi Shankar.

**Comment by Itsmemukesh** [comment]
Old defect with no detailed inputs. Closing the issue as no action is taken on this. Will create a fresh new issue if any changes are needed.
