### ISSUE TITLE
there is no way to connect with QSECOFR user

### ISSUE THREAD

**Issue by Alejandrodelgado** [ibm-cloud-docs/power-iaas#15]
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-connect-ibmi#ssh-tunneling

Two easy options, create a new user and include it in SECOFR with CRTUSRPRF
The other (I have not tested) is to  modify the sshd_config with "PermitRootLogin yes".

**Comment by prarredd** [comment]
Hello, the instructions are updated in the link: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-connect-ibmi#ssh-tunneling
Please verify and close the issue.

**Comment by Alejandrodelgado** [comment]
solved
