### ISSUE TITLE
MOL for IBM i

### ISSUE THREAD

**Issue by kbroussard** [ibm-cloud-docs/power-iaas#16]
The FAQs are incorrect.   
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-power-iaas-faqs#os-support
How does licensing work for the AIX, IBM i, or Linux operating systems?
The license for the AIX and IBM i operating systems is part of the overall cost for the service. You cannot use an existing license that you already purchased. The Power Systems Virtual Server service does not provide Linux stock images. You must bring your own Linux image (OVA format) and subscription. RHEL and SLES OVA images are currently supported.

We do have a MOL (movable) program where customers can bring their i-Series licenses to Power VS.  Please contact offering management for details.

**Comment by prarredd** [comment]
Updated MOL details in the topic: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-power-iaas-faqs#os-support
