### ISSUE TITLE
ISV Information

### ISSUE THREAD

**Issue by dianebbritton** [ibm-cloud-docs/power-iaas#18]
Need some guidance on which ISVs are supported on Power Virtual Server, or state the assumption that if it works on prep, it works in the cloud and you don't have to worry, retest. You just have to negotiate any license change directly with the ISV.

**Comment by prarredd** [comment]
ISV information is customer and vendor specific and the customers can contact the support or the ISV documentation for more details. ISV information can be varying and very dynamic which we cannot include in our docs. Thank you.
