### ISSUE TITLE
Power Systems Virtual Server - release note for July 2020 missed 

### ISSUE THREAD

**Issue by gabriela-garcia27** [ibm-cloud-docs/power-iaas#19]
This documentation is not available:

July 2020
The Power Systems Virtual Server instance supports the SAP NetWeaver and SAP HANA workload. For more information, see Getting started with SAP NetWeaver on IBM Power Systems Virtual Servers and Getting started with SAP HANA on IBM Power Systems Virtual Servers.

**Comment by prarredd** [comment]
Updated link: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-release-notes
