### ISSUE TITLE
Data Center list cut off

### ISSUE THREAD

**Issue by mpudota907** [ibm-cloud-docs/power-iaas#2]
Submitted by gcorneau-ibm

Comment: 
The three selection boxes for data center contents is cut off for the list of non-US data centers (in the section Hardware specifications). With the font size on my web browser it shows "Non-US (FRA04, FRA05, LON04, LON06, SY...)" and mouse over doesn't show the entire list.
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-about-virtual-server#hardware-specifications
Also, shouldn't there be somewhere on this page just a plain list of the all the available data centers?

**Comment by mpudota907** [comment]
@gcorneau-ibm i am recreating the issue because of some issue with this repository.

**Comment by mpudota907** [comment]
@gcorneau-ibm List of all the available data centers
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-power-virtual-server

**Comment by gcorneau-ibm** [comment]
What about the cut-off list on the link?  Attached is a screenshot: 
![DC_cutoff](https://user-images.githubusercontent.com/47122062/108108454-427e3d80-7056-11eb-9454-7e551eed5804.png)

**Comment by gcorneau-ibm** [comment]
Saw the latest update, looks good.  You can close this out.
