### ISSUE TITLE
Invalid link to PowerVS network architecture diagrams

### ISSUE THREAD

**Issue by strattner** [ibm-cloud-docs/power-iaas#20]
On this page: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-security

The last sentence has a link:

To understand the Power Systems™ Virtual Server connection methods, see [Network architecture diagrams](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-reference-architecture).

That link is not valid. It should probably use this link instead:
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-architecture-diagrams

**Comment by prarredd** [comment]
Network topic link is fixed and working fine. Thank you.
