### ISSUE TITLE
Procedure at https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-managing-network-interface

### ISSUE THREAD

**Issue by tschrenk-corp** [ibm-cloud-docs/power-iaas#21]
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-managing-network-interface

Can you explain in more detail what you were doing?
Can you show this with an example?

I tried to execute this procedure. An existing AIX LPAR 10.72.203.150 was assigned to an additional network and goit there 10.72.203.22.

Now I tried to configure the new IP address on adapter en1

Cannot ping 10.72.203.22  so assume it needs to be configured on adapter en1
private-DL | Private | 10.72.203.130 — 10.72.203.158 | 482 |  -- | -- | -- | -- | --
private-Megaport | Private | 10.72.203.2 — 10.72.203.30 | 483 -- | -- | -- | --

![Bildschirmfoto 2021-07-09 um 15 48 36](https://user-images.githubusercontent.com/36664716/125087854-247cac80-e0cd-11eb-96a7-53c70b6e017e.png)

Here the Subnets
<img width="1360" alt="Bildschirmfoto 2021-07-09 um 15 49 09" src="https://user-images.githubusercontent.com/36664716/125087918-378f7c80-e0cd-11eb-9dd8-54c4b8e99d71.png">

After executing smitty the LPAR could ping itself on 10.72.203.22  bit not remote machine 10.72.203.26

Remote machine was also not able to reach 10.72.203.22.

Tried it with smitty and command line. But it does not work.

**Comment by prarredd** [comment]
Hello.. Systems on a private network will require cloud connection (or opening of a service ticket) in order to configure the vlan for communication. There is already documentation on this, See:   Networking considerations
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-configuring-subnet
