### ISSUE TITLE
Do we need to add a note here on how data should not be shareable for IBM i?

### ISSUE THREAD

**Issue by sammagnum** [ibm-cloud-docs/power-iaas#22]
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-power-virtual-server
<img width="659" alt="image" src="https://user-images.githubusercontent.com/1140988/125459215-e6a7e2fe-c02b-4e79-ae75-34c74ef3c1b2.png">

**Comment by prarredd** [comment]
Added info for IBMi: 
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-power-virtual-server#configuring-instance
VM pinning : Select this option to pin your virtual machine. You can choose either a soft or hard pinning policy.
Learn more.
Note: When you create multiple instances of the virtual server, you must select On from the Shareable field for each data volume that you add. If you do not want the data volume to be shareable, you can add the data volume after you create the virtual server. **For IBM i OS you cannot have shareable data volumes.**
