### ISSUE TITLE
Creating a new image 'osType' parameter now accepts 'rhel' instead of 'redhat'

### ISSUE THREAD

**Issue by seemanthinibr** [ibm-cloud-docs/power-iaas#23]
**Describe the issue**
Create new image in PowerVS now accepts 'osType' value of 'rhel' instead of                                               
documented 'redhat'.  
                                         
**Expected behavior**
Document needs to be fixed to change "redhat "to "rhel"

**Additional context**

https://cloud.ibm.com/apidocs/power-cloud
![image](https://user-images.githubusercontent.com/56261199/130733522-450b955b-b192-488a-b273-edf8a7a4822b.png)

**Comment by seemanthinibr** [comment]
As this issue was reported by customer, customer wants to know when the documentation update will be made

**Comment by prarredd** [comment]
Hello. Thank you for pointing it out. the Docs have been updated. 
https://cloud.ibm.com/apidocs/power-cloud#pcloud-pvminstances-post
