### ISSUE TITLE
Broken link to "IBM i Disaster Recovery with IBM Power Systems Virtual Servers"

### ISSUE THREAD

**Issue by JefHoeberichts** [ibm-cloud-docs/power-iaas#25]
On page https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-ha-dr the link to 
IBM i Disaster Recovery with IBM Power Systems Virtual Servers : https://ibm.box.com/s/87ye48a4jskrsp7hxcij7ujbs3vemb0j

does not work.

**Comment by mpudota907** [comment]
Updated the broken links.
