### ISSUE TITLE
Power VS data centers table not rendered

### ISSUE THREAD

**Issue by clnperez** [ibm-cloud-docs/power-iaas#26]
**Describe the issue**
The table that used to show up as a table, shows up as markdown in a black box

**Expected behavior**
The table should be human-readable

**Additional context**
![Screenshot from 2021-10-06 14-10-04](https://user-images.githubusercontent.com/4493281/136267697-001cd51f-2381-4338-b86f-5eec36203d23.png)

**Comment by prarredd** [comment]
The table has been fixed and it is appearing fine now. Thanks.
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-power-virtual-server

**Comment by clnperez** [comment]
Thanks!
