### ISSUE TITLE
Need documentation regarding Considerations when reusing Volume names or VM names

### ISSUE THREAD

**Issue by seemanthinibr** [ibm-cloud-docs/power-iaas#27]
We need a documentation updated for PowerVS on Considerations when reusing Volume names or VM names, similar to that of PowerVC as described in https://www.ibm.com/support/pages/powervc-considerations-when-reusing-volume-names-or-vm-names.

**Comment by seemanthinibr** [comment]
Do we have any updates for this issue

**Comment by prarredd** [comment]
Hello I will check with dev team for inputs. This issue will be addressed post December.

**Comment by prarredd** [comment]
Updated topic with considerations while using volume names: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-power-virtual-server#reusing_volume_names
