### ISSUE TITLE
Linux networking section for SLES needs to be updated

### ISSUE THREAD

**Issue by mfriesenegger** [ibm-cloud-docs/power-iaas#28]
The [Linux networking](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-using-linux#linux-networking) section for SLES causes networking delays.  The problem does not exist when following the [Linux networking](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-linux-with-powervs#linux-networking) section for RHEL on a SLES instance.  Please update the Linux networking section for SLES.

**Comment by prarredd** [comment]
Updated for SLES: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-using-linux#linux-networking
