### ISSUE TITLE
broken link to the box

### ISSUE THREAD

**Issue by notras** [ibm-cloud-docs/power-iaas#28]
Link to IBM Power Virtual Server Virtual Private Network Connectivity (https://ibm.box.com/s/13qv6uo9ylhla6zh7ernerb49pko1160) return message - This shared file or folder link has been removed or is unavailable to you. Probably link expired and need update.

**Comment by mpudota907** [comment]
Updated the broken link. Now you can view or download tutorial PDF copy.
