### ISSUE TITLE
IBM i documentation assumes a minimum level of administration skill

### ISSUE THREAD

**Issue by acursons** [ibm-cloud-docs/power-iaas#29]
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-minimum-levels

The above page informs the user of minimum ptf requirements. However as a complete newby struggling to get to grips with the platform I have no idea how to achieve this feat. 

Step by step instructions would be great as I have also drawn a blank trying to find explicit instructions online.

**Comment by prarredd** [comment]
Updated with link where instructions are available on how to download PTFs.
