### ISSUE TITLE
Sizes on Pricing page are incorrect

### ISSUE THREAD

**Issue by mlobbes** [ibm-cloud-docs/power-iaas#3]
Sizes on this page do not match what is supported through the provisioning UI
https://cloud.ibm.com/docs/infrastructure/power-iaas?topic=power-iaas-pricing-virtual-server

**Comment by mpbagwel** [comment]
Sorry for the delay. I updated the text to match the provisioning UI. The update will go live on **December 2, 2019**. Thanks!

>IBM® Power Systems™ Virtual Server on IBM Cloud is offered in select regions with scale-out logical partitions (LPAR) up to 15 Cores and 384 GB of memory and also with enterprise LPARs up to 143 cores and 8192 GB of memory.
