### ISSUE TITLE
Do newer version of RHEL  work? The documentatin on version requirements seem out of date.

### ISSUE THREAD

**Issue by sammagnum** [ibm-cloud-docs/power-iaas#31]
> RHEL 8.1
>     RHEL 8.2
>     RHEL 8.3
>     RHEL 8.4
> 
> Ensure that you have the latest cloud-init version as on March 2021 for all the supported RHEL versions. If some of the RHEL versions (for example, RHEL 8.1 and RHEL 8.2) become out of support, you must obtain extended support from Red Hat. Follow the requirements of extended support and apply patches or updates as recommended by Red Hat. For more information about extended support, see [RHEL Extended Update Support (EUS) Overview](https://access.redhat.com/articles/rhel-eus?_ga=2.219577241.1038820138.1643906771-1059076850.1643906771).

Can we review this doc as 8.10 is now available?

**Comment by prarredd** [comment]
The versions for RHEL are up to date as PowerVS supports only 8.1 to 8.4 versions of RHEL currently.
