### ISSUE TITLE
Wrong links on https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-at-events

### ISSUE THREAD

**Issue by alexdevc** [ibm-cloud-docs/power-iaas#32]
The below links should be updated: 

For more information, see [IBM Cloud Activity Tracker with LogDNA](https://cloud.ibm.com/docs/Activity-Tracker-with-LogDNA?topic=Activity-Tracker-with-LogDNA-getting-started#getting-started).

To learn more, see [Starting the web UI through the IBM Cloud UI](https://cloud.ibm.com/docs/Activity-Tracker-with-LogDNA?topic=Activity-Tracker-with-LogDNA-launch#launch_step2).

these return:

Sorry, this content isn’t available.
It seems we can’t find what you’re looking for. Try the IBM Cloud Docs search to find information.

**Comment by prarredd** [comment]
Revamped topic and updated link: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-at-events
