### ISSUE TITLE
The Link to VPNaaS documentation is wrong in IBM Cloud UI

### ISSUE THREAD

**Issue by fghoraishi** [ibm-cloud-docs/power-iaas#33]
When I press the VPNaaS documentation link on the Power service VPN connection it take me to a wrong location.
the correct link is 

https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-VPN-connections

Please forward to development team

tks
Faad
IBM Lab Services

**Comment by prarredd** [comment]
Fixed. It links to the correct topic now.
