### ISSUE TITLE
Need to improve the documentation for Power VS VTL instantiation

### ISSUE THREAD

**Issue by acursons** [ibm-cloud-docs/power-iaas#34]
I attempted to follow the procedure to provision a Power VS VTL instance commencing from:

https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-virtual-tape-libraries

this links to the document:

https://cloud.ibm.com/media/docs/downloads/power-iaas/PowerVS_VTL_Overview.pdf

It is this document which I believe needs enhancing, as following it step by step leads to a problem as the VTL provisioned cannot be accessed until another document is completed. The above document contains the following:

"DSI Restore Setup
After you have the VTL deployed, storage allocated, optional COS connectivity, and a Windows instance for the console,
proceed to the document ‘Restore v6 Installation Guide for the IBM PowerVS Environment.pdf’ ."

which links to:

http://dynamicsolutions.com/support/assets/files/DSI%20Restore%20v6%20Installation%20Guide%20for%20the%20IBM%20PowerVS%20Environment.pdf

However it is necessary to read and understand the last 4 pages of the document Commencing with the section 'User Information' so that one can actually access the VTL in order to do the required configuration.

**Comment by prarredd** [comment]
Hello.. This document was created by the developer. Can you please elaborate on what are the exact changes you are looking for?

**Comment by acursons** [comment]
I would suggest something along the lines of:

"DSI Restore Setup
After you have the VTL deployed, storage allocated, optional COS connectivity, and a Windows instance for the console, it will be necessary to login to the VTL instance using the console to set a known root password. Details of how to perform this are documented in the 'User Information' section in the document ‘Restore v6 Installation Guide for the IBM PowerVS Environment.pdf’. Once the root password on the VTL instance is set the document may be followed from the start."

**Comment by prarredd** [comment]
VTL is suspended currently.
