### ISSUE TITLE
Link for configuring GRE tunnel not working

### ISSUE THREAD

**Issue by rgentyala** [ibm-cloud-docs/power-iaas#36]
[Configuring Generic Routing Encapsulation (GRE) tunnel](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-managing-cloud-connections#configure-gre-tunnel)

Power VS requires GRE tunnel in some cases. If a customer wants to connect from Power VS to VM Ware or Classic, they need to have few details handy if they want to do everything by themselves. These partial documentation doesn't lead them anywhere.

**Comment by prarredd** [comment]
Fixed link: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-configuring-subnet#cidr-notation
