### ISSUE TITLE
Placement group  text for a single VSI is confusing

### ISSUE THREAD

**Issue by bmlandman** [ibm-cloud-docs/power-iaas#37]
The  text from [this page](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-power-virtual-server) is confusing in regards to creation  of a Placement group.  The specific text is as follows:
`Placement group: If you are creating only one instance, you can choose the placement group to control on which host this instance will be hosted on. Select a placement group from the list. To create a new placement group select one of the following options:
Same server : Select this option to place the VM on the _same host._
Different server : Select this option to place the VM on a _different host_.`

If I understand placement groups correctly, it applies in practice to >1 virtual  machine. The text above makes reference to "same host" and "different host". Same or different from what? An existing instance in that Placement Group? That doesn't make sense as it's a new Placement Group. Maybe I'm misunderstanding something here?

**Comment by prarredd** [comment]
Hello Placement Groups in general applies to grouping more than 1 VMs you are correct. In the GUI there is a Placement Group option when you are creating a VM. Here you can specify if you want to place the new VM your creating in the same server or in a different server (you should have a placement group already created in the same server or in a different server). So you are selecting that PG depending on where you want to host the new VM. This topic explains only what you can do when creating a new VM. If you dont want to place it any PG then you can select None.

To create a new PG, you must goto the server placement group  tab. Here you can create a new placement group and also add existing VMs to this group. If you already have placement group created (in the server placement group  tab) then if you create 1 new VM you can add this VM to the existing PG in the same server. Or if you have a PG in a different server you can host it there as well. 
This topic has more details on creating PG: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-placement-groups

**Comment by bmlandman** [comment]
Thank  you for  the response  and explanation. The point I was trying to make is that  the text  in my  original post doesn't  make mention of _existing_  PGs when  you create the instance. Hence the confusion around "to create a new placement group..... same server.....Different server..." It might be a good idea,  too, to  include that link in the discussion  of placement groups when creating VMs.
