### ISSUE TITLE
Numerical postfix option description seemingly contains superfluous or erroneous text

### ISSUE THREAD

**Issue by bmlandman** [ibm-cloud-docs/power-iaas#38]
**Describe the issue**
A clear and concise description of what the issue is.

The text regarding the Numerical postfix option on  [this page](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-power-virtual-server)  is confusing - seemingly containing superfluous or erroneous text.  See text snippet below:
`Numerical postfix : _Select this option to host all instances on the same server_Select this option to add numbers after the name of the virtual server. If, for example, the first Power Systems Virtual Server name is Austin the next name for the virtual instance is Austin1.`

- Is something missing from the documentation? No
- Is the documentation confusing or misleading?  Yes
- Are there syntax or coding example errors? No

**Expected behavior**
A clear and concise description of what you'd like fixed.

The text description of Numerical prefix makes no reference to the hosting location of all instances on servers. If it's not the case with  postfix either, that text `Select this option to host all instances on the same server `should be removed from postfix.

**Additional context**
Add files, screenshots, links, and or examples about the issue.

**Comment by prarredd** [comment]
Fixed: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-power-virtual-server#configuring-instance
