### ISSUE TITLE
Dead Links on Page Managing VPN connections

### ISSUE THREAD

**Issue by cnett** [ibm-cloud-docs/power-iaas#39]
There are 3 dead links on the Managing VPN connections page (https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-VPN-connections&locale=en).  In the "Connecting to your on-premises network" Section are the Links:

- [Create an IKE policy](https://cloud.ibm.com/docs/power-iaas-cli-plugin?topic=power-iaas-VPN-connections#creating-IKE-policies).

- [Create an IPsec policy](https://cloud.ibm.com/docs/power-iaas-cli-plugin?topic=power-iaas-VPN-connections#creating-IKE-policies).

- [Create a VPN connection](https://cloud.ibm.com/docs/power-iaas-cli-plugin?topic=power-iaas-VPN-connections#creating-VPN-connections).

not valid ("Sorry, this content isn’t available.
It seems we can’t find what you’re looking for.").

**Comment by prarredd** [comment]
Fixed: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-VPN-connections#vpn-connecting-onpremise
