### ISSUE TITLE
How get accesss to the Power System Virtual Server Public IP

### ISSUE THREAD

**Issue by obustos** [ibm-cloud-docs/power-iaas#4]
Once the Virtual Server is created indicating a Public IP is desired. the IP is assigned but there is no documentation about how to get it working. Apparently some additional configuration is required but not documented. what is the following steps after get the Virtual Server up, with a public IP assigned but not responding ping, https, ssh or other protocols ? 
Off course once the virtual server is up. Through the console, ssh and https are activated.
Thanks

**Comment by mpbagwel** [comment]
@obustos Thanks for your feedback. Here is some information our docs provide about selecting a public network:

When you create a Power Systems Virtual Server, you can select a private network interfaces or a public network interface.

**Public network**

- Easy and quick method to connect to a Power Systems Virtual Server instance.
- IBM configures the network infrastructure to enable a secure public network connection from the internet to the Power Systems Virtual Server instance.
- Connectivity is implemented by using an IBM Cloud Virtual Router Appliance (VRA) and a Direct 
- Link Connect connection.
- Protected by firewall and supports the following secure network protocols:

- SSH
- HTTPS
- Ping
- IBM i 5250 terminal emulation with SSL (port 992)

https://cloud.ibm.com/docs/infrastructure/power-iaas?topic=power-iaas-about-power-virtual-server#apvs-public-and-private

https://cloud.ibm.com/docs/infrastructure/power-iaas?topic=power-iaas-creating-power-virtual-server
