### ISSUE TITLE
Clarify documentation. https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-connecting-networks#connecting-instance-colos

### ISSUE THREAD

**Issue by jxadro** [ibm-cloud-docs/power-iaas#40]
Hi.

In the URL https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-connecting-networks#connecting-instance-colos

You can read: IBM Cloud Connect is only available to IBM clients within the US.

I think it is important to clarify what means that sentence. I opened a IBM Cloud case and they were not aware of any restriction, in fact I'm connecting colocations from frankfurt.

Plese could you clarify what means that?

Thank you.

**Comment by prarredd** [comment]
Hello.. I spoke to the architect and he confirmed Cloud Connect  is available in US only. Another change has occurred that, it is part of Kyndryl now. So we have modified the topic accordingly:  
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-connecting-networks#connecting-instance-colos

**Comment by jxadro** [comment]
Hi @prarredd I think that could apply to Direct Link from customer network to Power Virtual Server colocation, not for connecting Power Virtual server network to IBM Cloud Network.

**Comment by jxadro** [comment]
May be I' not seeing the update

![image](https://user-images.githubusercontent.com/23421829/160424411-1688c8f3-dde0-4d16-8d23-38bc3ab159dc.png)

**Comment by prarredd** [comment]
Hi.. Yes the update I did was to say Cloud connection which is now renamed to Managed Networking services is available only in US. Let me check on the above point you have mentioned with the Architect.
