### ISSUE TITLE
A bit confused by the purposes of the two Network Diagrams topics

### ISSUE THREAD

**Issue by prb112** [ibm-cloud-docs/power-iaas#41]
A bit confused by the purposes of the two Network Diagrams topics 

https://github.com/ibm-cloud-docs/power-iaas/blob/master/network-architecture-nrt.md
https://github.com/ibm-cloud-docs/power-iaas/blob/master/network-architecture.md

The table of contents shows two *Network Architecture Diagrams" 
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-architecture-diagrams

Which one is authoritative? 

![image](https://user-images.githubusercontent.com/3016328/160166419-dcf611ad-d392-457b-9b00-52ab52f41e71.png)

**Comment by prarredd** [comment]
Hello. It was published by mistake. I have corrected it now. There is only one N/W topic.
