### ISSUE TITLE
Clarification of available storage types in FAQ

### ISSUE THREAD

**Issue by marobbo** [ibm-cloud-docs/power-iaas#42]
In the FAQ under "What are the available storage types in the storage area network (SAN)?" the documents mention that

`A VM cannot have disks from both storage types.`

While this is true on provisioning it appears you can now add a volume of the other storage types after the VM has been provisioned. Suggest updating https://github.com/ibm-cloud-docs/power-iaas/blob/master/faq.md to reflect that.

**Comment by Itsmemukesh** [comment]
Change updated in https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-power-iaas-faqs#storage
"A VM cannot have disks from both storage types while provisioning. But, you can add a volume of the other storage types after the VM has been provisioned."
