### ISSUE TITLE
Add Maxava to 2 areas of this document.

### ISSUE THREAD

**Issue by ashleygiddings** [ibm-cloud-docs/power-iaas#43]
Can you please add the line below to both the Application-specific replication and Third-party vendor tools, underneath MIMIX from Syncsort:

**Maxava HA**

Thank you, Ash.

**Describe the issue**
A clear and concise description of what the issue is.

- Is something missing from the documentation?
- Is the documentation confusing or misleading?
- Are there syntax or coding example errors?

**Expected behavior**
A clear and concise description of what you'd like fixed.

**Additional context**
Add files, screenshots, links, and or examples about the issue.

**Comment by prarredd** [comment]
Hello. Are you referring to a Power Virtual Server documentation topic? It would help to get a link to the exact topic you are requesting the change for. Please let us know.

**Comment by ashleygiddings** [comment]
Hi, yes the link to the document is https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-migration-strategies-power 

It would be great to have the works **Maxava HA** added to this list in the section below:

Application-specific replication

Applications might have replication mechanisms that can sync multiple environments. These options are commonly used for application-specific replication:

Db2 HADR
Oracle Data Guard
Oracle Goldengate
iCluster
MIMIX from Syncsort

**Comment by prarredd** [comment]
@Mukesh: Please proivde this link to Saritha Vinod and check on adding Maxava HA to the list.https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-migration-strategies-power#replication-app

**Comment by Itsmemukesh** [comment]
@ashleygiddings Added Maxava HA in the topic https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-migration-strategies-power#replication-app

**Comment by ashleygiddings** [comment]
@Itsmemukesh Thank you for that. "Maxava HA" also requires adding to the 'Third-party vendors and tools' section on that same page please.
