### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by Alejandrodelgado** [ibm-cloud-docs/power-iaas#46]
this link is directed to a wrong page
You can use a monthly subscription model when you purchase PowerHA SystemMirror for AIX Standard Edition. For more information, see [Standard Edition monthly pricing options](https://www-01.ibm.com/common/ssi/ShowDoc.wss?docURL=/common/ssi/rep_ca/8/897/ENUS219-288/index.html&request_locale=en).

Must be this one?
https://www.ibm.com/downloads/cas/US-ENUS219-288-CA/name/ENUS219-288.PDF

**Comment by Itsmemukesh** [comment]
Hello @Alejandrodelgado 
Both links point to exactly the same information. The publication date is the same. 

Let me know if you mean any other link.
