### ISSUE TITLE
"Direct Link (2.0) Connect" is available in other countries than US.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/power-iaas#47]
Hello,
I believe this description is not correct.

https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-architecture-diagrams
>IBM Cloud Direct Link (2.0) Connect is only available to IBM clients within the United States.

What is only available in the US is "IBM Cloud Connect", which is a different service from "Direct Link (2.0) Connect".

It is correct that "IBM Cloud Connect" is only available in the US.
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-connecting-networks

"Direct Link (2.0) Connect" for PowerVS is available in many countries.
https://cloud.ibm.com/docs/dl?topic=dl-locations#connect-locations

Thank you,

**Comment by Itsmemukesh** [comment]
@ytama 
Thanks for the feedback. The changes have been made: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-architecture-diagrams#network-reference-architecture-onprem
