### ISSUE TITLE
Update of the documentation to connect Power VS with x86

### ISSUE THREAD

**Issue by tschrenk-corp** [ibm-cloud-docs/power-iaas#48]
To connect the Power Colo with classic the procedure has changed. At https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-configuring-subnet there is stated:

For more information, see tutorial on [IBM Power Systems Virtual Server integration with x86-based workloads](https://cloud.ibm.com/media/docs/downloads/power-iaas-tutorials/PowerVS_and_x86_Integration_Tutorial_v1.pdf).

The procedure has changed as now a Direct link is not created manually but from within Power VS a connection is established with an optional GRE tunnel above.

I would recommend a short tutorial on how to connect Power VS with Classic. 

I am volunteering to test the procedure :-)

In a previous engagement the procedure was
1. Created PowerVS Service
2. Create private Subnet
3. Create onnecton from Power -> Classic (no GRE) -> DL was created in background
4. At Gateway (e.g. Vyatta) create a static route to the PowerVS subnet

After doing these steps I cannot reach from LPAR -> Gateway nor Gateway -> LPAR

Some months ago this worked:
1. Created PowerVS Service
2. Create A POWERVS DL 2.0
3. Have the cloud team connet the DL end with the Power subnet
4. At Gateway (e.g. Vyatta) create a static route to the PowerVS subnet
5. ping LPAR->Vayatta works, ping Vyatta -> LPAR works

So it would be nice to have a quick procedure

**Comment by prarredd** [comment]
@mukesh Please forward this to Rakesh and get his input.

**Comment by fghoraishi** [comment]
Step 2 needs to stay: 
2. Attach the private subnet to the Cloud Connection DL in the Cloud Connection DL

No need to reach to support as this is now automated.

Faad

**Comment by Itsmemukesh** [comment]
Closing this issue. Old defect with no action taken.
