### ISSUE TITLE
Custom ISO price - https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-pricing-virtual-server#pricing-operating-systems

### ISSUE THREAD

**Issue by jxadro** [ibm-cloud-docs/power-iaas#49]
Hi,

https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-pricing-virtual-server#pricing-operating-systems

I think in this page it should be clarified that custom images ISO deployed on the Internal boot image repository is not charged.

This was discussed in the ticket CS2885846

**Comment by Itsmemukesh** [comment]
Checking with Moises & Paul Finley.

**Comment by Itsmemukesh** [comment]
This is an old defect.
New documentation can be found here: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-pricing-virtual-server-on-cloud#pricing-operating-systems
