### ISSUE TITLE
Content isn't available

### ISSUE THREAD

**Issue by affian** [ibm-cloud-docs/power-iaas#50]
Hi team, I am reading the documentation for PowerVS to on-premises network architecture [here](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-architecture-diagrams#network-reference-architecture-directlink).
I noticed the link to "[Connect-to-Classic infrastructure by using IBM Direct Link](https://cloud.ibm.com/docs/gateway-appliance?topic=power-iaas-network-architecture-diagrams#network-reference-architecture-privatessl)" points to a blank page.

**Comment by Itsmemukesh** [comment]
Hey @affian 
Thanks for pointing out the broken link. It is now fixed.
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-architecture-diagrams#network-reference-architecture-privateipsec
