### ISSUE TITLE
"IBM Cloud Connect" is correct, not "Direct Link Connect". These are two different services.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/power-iaas#51]
Hello,
In the description below, "IBM Cloud Connect" is correct, not "Direct Link Connect". These are two different services.

https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-architecture-diagrams#network-reference-architecture-onprem
> Direct Link Connect is a managed network service that uses Megaport services. This service is available only in the United States. 

Thank you,

**Comment by Itsmemukesh** [comment]
@ytama 
Thanks for the feedback. The changes have been made: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-architecture-diagrams#network-reference-architecture-onprem
