### ISSUE TITLE
Direct Link (2.0) Connect does not provide a direct connection from on-premises to PowerVS.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/power-iaas#52]
Hello,

In the description below, Direct Link (2.0) Connect does not provide a direct connection from on-premises to PowerVS, so the "or Direct Link (2.0) Connect" is unnecessary.

https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-architecture-diagrams#network-reference-architecture-onprem
> You can also use Megaport or Direct Link (2.0) Connect to connect your on-premises network to Power Systems Virtual Server directly.

Thank you,

**Comment by Itsmemukesh** [comment]
@ytama 
Thanks for the feedback. The changes have been made: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-architecture-diagrams#network-reference-architecture-onprem
