### ISSUE TITLE
Inconsistent explanations for GRE configuration settings between PowerVS and GW appliance/NSX...

### ISSUE THREAD

**Issue by notras** [ibm-cloud-docs/power-iaas#53]
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-cloud-connections#gre-configuration-example
Provided descriptions not clear and confusing when you try to implement it in practice. 

Link to pdf tutorial have outdated recommendations because ticket not needed anymore for GRE setup and process looks different.

On the Power VS connection side to Classic in UI only two fields available - GRE Destination IP and GRE subnet and not four fields like in documentation.

Also IBM provide for connection, User IP address and IBM IP address in /30 subnet but no direct mapping with Power VS source and PowerVS tunnel IP provided between this /30 subnet and GRE configuration settings in the docs.

GRE Subnet:       : 172.16.3.0/29 (GRE subnet that you chose) what does it mean?
In the provided example this IP range overlapping PowerVS tunnel IP  and VRA tunnel IP and probably User IP address and IBM IP address /30 subnet. But no explanation provided about it. 

For BGP configuration provided PowerVS ASN number 64999 but not provided details about BGP neighbour, without it not possible to setup BGP on Gateway Appliance.

**Comment by Itsmemukesh** [comment]
Closing the issues as this is an old defect. Please create a new issue if any changes are needed for docs.
