### ISSUE TITLE
Lab on Snapshot / Cloning

### ISSUE THREAD

**Issue by tschrenk-corp** [ibm-cloud-docs/power-iaas#54]
While the process of initiating a snapshot and creating a clone are generally described I would find a hands-on Lab useful to fully understand and see the output of the commands in the various steps.

**Comment by Itsmemukesh** [comment]
Could you elaborate more on your requirements? Please refer to https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-volume-snapshot-clone for information.

**Comment by tschrenk-corp** [comment]
The principle is described in the documentation. To really understand it it would be helpful to really do it and pack this as a kind of Lab in a small use case. This would help people to understand it and enable them to better use it in the field.

1. Create a PowerVS Service
2. Create a subnet
3. Provision an instance
4. Configure a clone
5. delete source data
6. Restore from clone disk
7. Verify that the LPAR is again up and running.
