### ISSUE TITLE
The example for Shared Procesor Pool is incorrect.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/power-iaas#55]
Hello,
In PowerVS, the core-to-vCPU ratio is 1:1, so I do not think the configuration example shown in Table 1 is possible.
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-manage-SPP

If VM1 Maximum cores is 5 as shown in Table 1, Entitled capacity needs to be at least 4.25.
Similarly, if the Maximum cores of VM2 is 6, the Entitled capacity needs to be at least 5.25.
Therefore, reserved cores in shared processor pool must be at least 10 (Round up the result of 4.25+5.25).

Thank you,

**Comment by Itsmemukesh** [comment]
SPP topic updated
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-manage-SPP
