### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by mraquinn** [ibm-cloud-docs/power-iaas#57]
In this section: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-migration-strategies-power#migration-icos

The two links labelled:
[Configuring YUM and creating local repositories on IBM AIX](https://developer.ibm.com/technologies/systems/articles/configure-yum-on-aix/)
[Python for AIX](http://www.aixtools.net/index.php/python)

Do not work.

**Comment by Itsmemukesh** [comment]
The python link is now fixed.
The "Configuring YUM and creating local repositories on IBM AIX" was not found.

https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-migration-strategies-power
