### ISSUE TITLE
Power Pricing Seems Off

### ISSUE THREAD

**Issue by he1d1** [ibm-cloud-docs/power-iaas#58]
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-pricing-virtual-server

When you multiply the `Hourly rate (Processor type)`, by 730, the result seems inconsistant, and isn't equal to the monthly charge.

I'm just curious where this difference comes from.

**Comment by Itsmemukesh** [comment]
All prices mentioned on the pricing page are illustrative and do not represent the actual amounts used for billing. To calculate the exact pricing, use the [IBM cost estimator](https://cloud.ibm.com/estimator).
