### ISSUE TITLE
Add HTTP *ADMIN ports and port descriptions

### ISSUE THREAD

**Issue by wbowers23** [ibm-cloud-docs/power-iaas#59]
Hello,

I support IBM i Access in the IBM i Global Support Center and I have a customer commenting on document:

https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-connect-ibmi

They are asking that the common HTTP *ADMIN ports like 2001 (2010 secure) for HTTPAdmin; 2002 (2003 secure) for Navigator for i; 2004 (2005 secure) for Heritage Navigator for i, 2006 for Digital Certificate Manager.

They are also asking that the ports be listed with a description like I have shown above.  I think the following IBM i Support document could be linked to meet that request:    https://www.ibm.com/support/pages/node/644775

Regards,

Wayne Bowers
IBM i Global Support

**Comment by Itsmemukesh** [comment]
Updated SSH command
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-connect-ibmi#ssh-tunneling
