### ISSUE TITLE
Link is broken.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/power-iaas#60]
Hello,

https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-app-modernization-using-RedHat-openshift&locale=en
On this page, the following link is broken.

"Deploying Red Hat OpenShift Container Platform 4.x on IBM Power Systems Virtual Servers"(https://developer.ibm.com/components/ibm-power/series/deploy-ocp-cloud-paks-power-virtual-server/)

Correct URL would be this.
https://developer.ibm.com/series/deploy-ocp-cloud-paks-power-virtual-server/

Thanks,

**Comment by Itsmemukesh** [comment]
Fixed https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-app-modernization-using-RedHat-openshift&locale=en
