### ISSUE TITLE
Comment on issue #54

### ISSUE THREAD

**Issue by tschrenk-corp** [ibm-cloud-docs/power-iaas#63]
As the issue was closed and I cannot reopen I just paste the comment here.
--
The principle is described in the documentation. To really understand and be able to show it to a client, it it would be helpful to really do it and pack this as a kind of Lab in a small use case. This would help people to understand it and enable them to better use it in the field.

Create a PowerVS Service
Create a subnet
Provision an instance
Configure a clone
delete source data
Restore from clone disk
Verify that the LPAR is again up and running.

**Comment by Itsmemukesh** [comment]
Closing this issue as this is an old one. Lab services tutorials are now not referenced from IBM Cloud docs.
