### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by JoachimFischer** [ibm-cloud-docs/power-iaas#64]
link to network architecture diagram is broken

To understand the Power Systems™ Virtual Server connection methods, see [Network architecture diagrams](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-reference-architecture).

**Comment by Itsmemukesh** [comment]
Fixed
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-security
