### ISSUE TITLE
Section "Network Considerations" asks for information which is not available in the GUI

### ISSUE THREAD

**Issue by jobgitmww** [ibm-cloud-docs/power-iaas#65]
When deploying a private subnet in Power VS a ticket must be opened to ask for the gateway configuration of this subnet to allow internal communication only. 

The according section "Network Considerations" contains the table 1 with sample information which the user is supposed to get from the Subnet configuration and which must be provided in the ticket. 

The following information is a) not provided by the Subnet configuration view in the GUI (as wrongly written in the documentation and b) this information is not required by our support to perform the configuration. Consequently the following two entries should be removed from the documentation / table 1:

1: MAC address
2: IP address

Martin Weidauer

**Comment by jobgitmww** [comment]
I just learned, that the documentation section is referring to the interface information of an instance which is deployed into a subnet. But it's not stated in the documentation which just refers to "the GUI". Since the ticked which needs to be opened is related to a subnet I concluded that all information is available in the subnet GUI. Clarification of the text is required.

**Comment by jobgitmww** [comment]
Additionally this section of the documentation does not mention a VPNaaS connection which also would automatically configure a gateway to the subnet. This should be added.

**Comment by Itsmemukesh** [comment]
Doc updated and pushed to test site: https://test.cloud.ibm.com/docs/power-iaas?topic=power-iaas-configuring-subnet#networking-considerations
Changes will be pushed to prod in the next prod push (~June)
