### ISSUE TITLE
GRS controller specification are missing

### ISSUE THREAD

**Issue by bkoohi** [ibm-cloud-docs/power-iaas#67]
Hi There, there is a pair GRS controller requirement in two sites. Specifications for these lpars ( mem, cpu , storage and OS licenses type ) are missing from this doc:
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-getting-started-GRS

Thanks
Behzad

**Comment by Itsmemukesh** [comment]
This issue is not valid.
Replication is at the storage level. There is no predefined specification for mem, cpu at lpar level.

Thanks
