### ISSUE TITLE
duplicate sentences

### ISSUE THREAD

**Issue by bcgong** [ibm-cloud-docs/power-iaas#69]
Planning a workload migration to an IBM POWER8, POWER9, or POWER10 system
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-system-migration

When workloads are deployed on a new system, you must pay attention to its configuration and tuning to achieve the expected performance. Power Systems Virtual Server uses different IBM Power Systems: E880 (9119-MHE), E980 (9080-M9S), S922 (9009-22A) . ~Power Systems Virtual Server uses different IBM Power Systems: E880 (9119-MHE), E980 (9080-M9S), and S922 (9009-22A).~ For more information, see [Hardware specifications](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-about-virtual-server#hardware-specifications).

Please remove the above duplicate sentence : `Power Systems Virtual Server uses different IBM Power Systems: E880 (9119-MHE), E980 (9080-M9S), and S922 (9009-22A).`

**Comment by Itsmemukesh** [comment]
Thanks for the feedback.
Changes are incorporated.
https://test.cloud.ibm.com/docs/power-iaas?topic=power-iaas-system-migration
