### ISSUE TITLE
Location Network Providers

### ISSUE THREAD

**Issue by mpudota907** [ibm-cloud-docs/power-iaas#7]
Submitted by: thomasmatter

Comment:
Under Networking > Direct Link Connect for Power Systems Virtual Servers > Location > Chart> Network Providers
"IBM Power Virtual Server" is listed as a network provider. That is clearly inaccurate.
Further, the networking diagrams for this are overly complicated. As a technical seller for IBM Cloud neither I nor my customers can make sense of the diagrams - there is a lot of noise. For the networking piece of this, for the most part all we need to know is options on how to connect a) Power Colo to customer on prem b) Power Colo to PoP/DC c) Power Colo to another colo
The existing diagrams include so many pieces it's almost impossible to discern which pieces a customer needs to purchase and setup vs which pieces are included. I had a customer look at these and come to me saying "I just want my on prem network to connect to power cloud, we don't have any other IBM Cloud". Even as an IaaS SME it look me a fair while to figure out which diagram was relevant even though I know how to connect.
tl;dr These network diagrams need to be simplified
Thomas Matter
Technical Sales
CSI/COMMS Market NA

**Comment by mpudota907** [comment]
@thomasmatter Updated the network architecture diagrams topic. 
Can please have a look and share your feedback. Feedback helps to keep the topic updated and relevant.
Link: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-reference-architecture

**Comment by prarredd** [comment]
Assuming there are no more comments, closing the issue.
