### ISSUE TITLE
E950 Not relevant to Power Systems Virtual Server

### ISSUE THREAD

**Issue by bcgong** [ibm-cloud-docs/power-iaas#70]
Implementing SAP NetWeaver and SAP HANA in the Power Systems Virtual Server environment
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-power-virtual-server#sap_netweaver_hana

On IBM Power Systems ~E950~ and E980 that are running in a multiple VM environment with at least one SAP HANA production system, you can deploy up to sixteen VMs per physical server with dedicated or dedicated-donating processor cores.

____________________________

In the above, `E950` has nothing to do with the Power Systems Virtual Server environment. That needs to be corrected.

**Comment by Itsmemukesh** [comment]
Thanks for the feedback.
Changes incorporated. https://test.cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-power-virtual-server#sap_netweaver_hana
