### ISSUE TITLE
Price Information is missing

### ISSUE THREAD

**Issue by JoergThomann** [ibm-cloud-docs/power-iaas#71]
Hi,
I can't find any price information for VPN Connection.
There is no documentation (not public, nor IBM internal), where I can find the exact pricing. 
Please update this page with the current pricing for a VPN connection.
Thank you.

**Comment by Itsmemukesh** [comment]
Hi,
We have added a new section for VPN pricing on the pricing page.
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-pricing-virtual-server#pricing-vpn

Let me know if there is anything missing. We will take a look at it.
