### ISSUE TITLE
Incorrect capitalization for Power systems (new with Power10)

### ISSUE THREAD

**Issue by gcorneau-ibm** [ibm-cloud-docs/power-iaas#75]
With the advent of Power10, the proper capitaliztion when Power10 is included on a page/presenatation/whitepaper is Power8, Power9, and Power10.  If Power8/9 were alone, you could use the old POWER8 or POWER9.
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-system-migration

**Comment by Itsmemukesh** [comment]
I have only changed the capitalization in the heading https://test.cloud.ibm.com/docs/power-iaas?topic=power-iaas-system-migration
The other isolated instances are POWER6/7/8/9 and are kept as is.
The changes are in test currently, and will push to production in the next prod push cycle.

Thanks
