### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by bcgong** [ibm-cloud-docs/power-iaas#76]
Please correct the below typo :
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-VPN-connections#powervs-support-vpn

Power Systems Virtual Server supports multiple `sworkspace` from the same account. 

==>  `sworkspace` should be corrected as `workspaces`

**Comment by Itsmemukesh** [comment]
Thanks for the changes. Corrections are done and changes are pushed to production
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-VPN-connections#powervs-support-vpn
