### ISSUE TITLE
BGP ANS are wrong in this Doc

### ISSUE THREAD

**Issue by fghoraishi** [ibm-cloud-docs/power-iaas#79]
BGP for WDC06 is no longer 64999. It is 4206000012.

Same with other PowerVS locations.

Please update the doc.

Faad

**Comment by fghoraishi** [comment]
i am with IBM at faad.ghoraishi@ibm.com

Faad

**Comment by Itsmemukesh** [comment]
Hi Faad,

The ASN for WDC06 is 64999, for regular DLs and manual config.

4206000012 and  4206000013 are the ASNs for TGW in WDC06.

**Comment by fghoraishi** [comment]
Thanks for the information.
Is this info updated in the DL2.0 documentation?
I canot find it in IBM Cloud.

https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-ordering-direct-link-connect&mhsrc=ibmsearch_a&mhq=BGP+ASN￼

Thanks
Faad

**Comment by Itsmemukesh** [comment]
I won't be able to answer about DL doc. Its maintained by another author.
