### ISSUE TITLE
Browser image import instructions are wrong on deploy page

### ISSUE THREAD

**Issue by smatzek** [ibm-cloud-docs/power-iaas#8]
Page and section:
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-deploy-custom-image#upload-custom-boot

The upload custom boot image section has incorrect field help. In particular the image file name field says you must use the fully qualified path of the COS image. Doing so gives you field validation errors and you cannot click the Import button.

The field help is also missing fields like "Bucket Name".

I believe the field help on this page should be removed and replaced with the field help from this page, which looks correct:
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-importing-boot-image#console-import-image

Or the whole import section on the deploy-custom-image page should be removed and the import boot image page be linked to.

**Comment by mpudota907** [comment]
@smatzek Thank you for feedback. Updated topic.
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-deploy-custom-image#upload-custom-boot
