### ISSUE TITLE
import/export no indication of duration of processes

### ISSUE THREAD

**Issue by ibmrcruicks** [ibm-cloud-docs/power-iaas#8]
very significant lag (30-90 minutes) between UI reporting successful Import or Export of boot image
documentation should indicate expectation of likely delay. 
User interface needs additional progress/state information to show that activity is actually happening

**Comment by mpbagwel** [comment]
@ibmrcruicks Hi Ross, thanks for opening an issue. What was the size of the boot image? I just want to make sure the import/export process is behaving correctly. Obviously, larger boot images will take longer to import/export. I'll add something to the documentation and get with my UI team to see if we can implement a mechanism that indicates progress.

**Comment by ibmrcruicks** [comment]
it was an 80GB image, which compressed down to a ~10GB .OVA.gz object.
export docs/info also don't tell you what the object name extension will be, but the import form requires a specific object extension.
any reason why the COS instance isn't made selectable in export/import dialogs? the user could then select from available buckets, or add a new one. (specifying an non-existent bucket could be caught before submitting the export) also - the use of key+secret requires the user to have generated COS credentials with HMAC: true -- I don't see that requirement anywhere.

**Comment by mpbagwel** [comment]
@ibmrcruicks I made a few changes to our import/export pages and also added a note about the significant delay. As for your UI suggestion about the progress feature, our team plans to incorporate something here in the near future. We'll need to investigate your other suggestion about having the COS instance appear in the export/import dialogs as that would require cross-service integration. And just FYI... this repo is more for documentation issues and suggestions. But appreciate all feedback!

https://cloud.ibm.com/docs/infrastructure/power-iaas?topic=power-iaas-deploy-custom-image
https://cloud.ibm.com/docs/infrastructure/power-iaas?topic=power-iaas-capturing-exporting-vm
https://cloud.ibm.com/docs/infrastructure/power-iaas?topic=power-iaas-importing-boot-image

**Comment by mpbagwel** [comment]
**The issue has been resolved. If something was missed or more work is required, please reopen the issue.**
