### ISSUE TITLE
Erroneous statement about private subnet communication

### ISSUE THREAD

**Issue by smatzek** [ibm-cloud-docs/power-iaas#80]
**Describe the issue**
This page: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-configuring-subnet
Contains the following false statement:
_"You must open a [support ticket](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-getting-help-and-support) against Power Systems Virtual Servers to configure the private network in Power Systems Virtual Server infrastructure. For example, if you add a subnet 172.10.10.0/24 from user interface, and if this use case requires communication between the virtual server instances that are attached to the subnet, you must open a support ticket and provide the following subnet information that is displayed in the user interface."_

This statement is false. You do not need to open a support ticket to have communication between virtual servers on the same private subnet in Power Virtual Server. This happens automatically and I've tested it out in the last couple weeks. 

**Expected behavior**
Remove the false statement.

**Comment by Itsmemukesh** [comment]
Since you have kept the "support ticket" para in your PR, I have modified it a little.
See the changes in test: https://test.cloud.ibm.com/docs/power-iaas?topic=power-iaas-configuring-subnet#networking-considerations

Let me know if you need any changes.

**Comment by smatzek** [comment]
As I read that networking section more, it just gets more confusing. I think it is blending old connection requirements with the newer things like cloud connections. It also talks about setting up routing between two Power Virtual Server instances (workspaces), and using Direct Links, etc. It may be best to either remove this section altogether now that the "Network Diagrams" page is in place, or replace it with a brief section on using cloud connections and with transit gateway to allow communication with the rest of IBM Cloud, x86s, and other Power Virtual Server workspaces.

**Comment by Itsmemukesh** [comment]
Removed "Network consideration" section

**Comment by smatzek** [comment]
Looks good. Thanks!
