### ISSUE TITLE
Incorrect statements about VPE connectivity

### ISSUE THREAD

**Issue by smatzek** [ibm-cloud-docs/power-iaas#81]
**Describe the issue**
This page: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-architecture-diagrams is outdated and now contains incorrect statements about VPEs.

In particular it states:
_" You cannot access endpoint networks (services and infrastructure services) and Virtual Private Endpoints (VPEs) from your Power Systems Virtual Server subnets. The types of endpoint networks are as follows:"_

VPEs are now accessible from within Power Virtual Server and are the preferred way to access cloud services instead of using proxies.

The statement above should be fixed to remove VPEs from the list.
This line should also be removed from the bulleted list below it: _"VPEs - Enables connection to supported IBM Cloud services by using the IP addresses allocated from a subnet within your VPC. For more information, see [VPE supported services](https://cloud.ibm.com/docs/vpc?topic=vpc-vpe-supported-services). Two infrastructure services of interest are NTP and IBM Cloud Object Storage."_

Step 4 should be updated. It currently states:
_"If you want to access the endpoint network, use a VPC virtual server instance to proxy the endpoint services. For example, a virtual server that is running Nginx can proxy HTTPS to and from IBM Cloud Object Storage. A virtual server that is running NTP services (synchronized with time.adn.networklayer.com) can be used as a time source for Power Systems Virtual Server instances."_

It is still necessary to use a proxy for cloud service endpoints, so the statement should stay but it should be changed to remove COS and NTP, both of which support VPE. Something like this:

"4. Create VPEs for services of interest such as DNS, NTP, and IBM Cloud Object Storage.  For more information, see [VPE supported services](https://cloud.ibm.com/docs/vpc?topic=vpc-vpe-supported-services). 

5. If you want to access the endpoint network, use a VPC virtual server instance to proxy the any required endpoint services that do not support VPEs. "

**Comment by Itsmemukesh** [comment]
Changes added and pushed to test: https://test.cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-architecture-diagrams#network-reference-architecture-vpc

**Comment by smatzek** [comment]
This bullet point still needs to be removed from the https://test.cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-architecture-diagrams#network-reference-architecture-vpc section under #35 

> VPEs services. For more information, see [VPE supported services](https://test.cloud.ibm.com/docs/vpc?topic=vpc-vpe-supported-services).
> 
> If you want to access the endpoint network, use a VPC virtual server instance to proxy the endpoint services.

**Comment by Itsmemukesh** [comment]
bullet point removed.
https://test.cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-architecture-diagrams#network-reference-architecture-vpc

**Comment by smatzek** [comment]
The changes look good. Thanks!
