### ISSUE TITLE
Getting started points users to manual Direct link process

### ISSUE THREAD

**Issue by smatzek** [ibm-cloud-docs/power-iaas#82]
**Describe the issue**
The getting started page, https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-getting-started, has an optional step 5:

_"(Optional) If you want to use a private network to connect to a Power Systems Virtual Server instance, you must order the [Direct Link Connect](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-ordering-direct-link-connect#steps-to-order-direct-link-connect) service. You cannot create a private network during the VM provisioning process. You must first use the Power Systems Virtual Server user interface, command line interface (CLI), or application programming interfaced (API) to [create one](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-configuring-subnet)."_

This process is the older, more manual process. The "easy" path is to use Cloud connections where the ordering of the direct links is automatic. This step should be changed to something like this:
_"(Optional) If you want to use a private network to connect to a Power Systems Virtual Server instance, you must either create cloud connections see, [Managing IBM Cloud Connections](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-cloud-connections), or order a [Direct Link Connect](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-ordering-direct-link-connect#steps-to-order-direct-link-connect) service. You cannot create a private network during the VM provisioning process. You must first use the Power Systems Virtual Server user interface, command line interface (CLI), or application programming interfaced (API) to [create one](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-configuring-subnet)."_

**Comment by Itsmemukesh** [comment]
Changes added and pushed to test: https://test.cloud.ibm.com/docs/power-iaas?topic=power-iaas-getting-started#before-you-begin
Let me know if you need any changes.

**Comment by smatzek** [comment]
Looks good. Thanks!
