### ISSUE TITLE
Change the order of the Network section articles

### ISSUE THREAD

**Issue by smatzek** [ibm-cloud-docs/power-iaas#83]
The Network section of the documentation has the current document order:
![image](https://github.com/ibm-cloud-docs/power-iaas/assets/13350259/fd866e66-66a1-4788-a9bd-15c0421b9cd6)

The top item in this list should be "Network architecture diagrams" because it lists out the typical network architectures and gives context for the other articles.

The second item in the list should be "Configuring and adding a private network subnet" because all the remaining items in the networking section are in support of connecting to/from your private networks.

The third item in the list should be "Managing IBM Cloud connections" because IBM Cloud connections should be the most commonly used way to connect to other IBM Cloud and on-prem services.

**Comment by Itsmemukesh** [comment]
Toc updated.
https://test.cloud.ibm.com/docs/power-iaas

**Comment by Itsmemukesh** [comment]
Further changes made as follows:

1. network arch diagram
2. configuring subnets
3. managing IBM cloud connections
4. Getting started with PER
5. Ordering direct link
6. Then the rest.

**Comment by smatzek** [comment]
The changes look good. Thanks!
