### ISSUE TITLE
Incorrect statement about Cloud connections and workspaces

### ISSUE THREAD

**Issue by smatzek** [ibm-cloud-docs/power-iaas#84]
**Describe the issue**
The documentation at this page, https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-cloud-connections#powervs-support-cloud-connections, states:

> Power Systems Virtual Server supports multiple workspaces from the same account. However, any given IBM Cloud connection can be used by only one workspace. If you want to configure a setup with multiple workspaces for the same account and if you want these workspaces to share an IBM Cloud connection, open an IBM Support case.

This statement is not true and should be removed or update to reflect the current support reality. I have created a second workspace in “Location: Dallas” and it automatically re-used an existing Cloud Connection I had setup in a separate workspace in Dallas.

**Comment by Itsmemukesh** [comment]
Changes added and pushed to test: https://test.cloud.ibm.com/docs/power-iaas?topic=power-iaas-cloud-connections#powervs-support-cloud-connections

Let me know if you need any changes.

**Comment by smatzek** [comment]
Looks good, thanks!
