### ISSUE TITLE
docs powerVS: A hyperlink within a FAQ is broken

### ISSUE THREAD

**Issue by ketanpancholi** [ibm-cloud-docs/power-iaas#89]
The link to "Configuring IBM Power Systems Virtual Servers" in this FAQ is broken

https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-power-iaas-faqs#configuring

```
How do you set up customer site access to a private network by using VPN?

For more information, see [Configuring IBM Power Systems Virtual Servers](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-configuring-power).
```

**Comment by Itsmemukesh** [comment]
Thanks for the changes @ketanpancholi 
I have made updates in the test site: https://test.cloud.ibm.com/docs/power-iaas?topic=power-iaas-power-iaas-faqs#configuring

I will push it to production if the changes look good to you.

**Comment by ketanpancholi** [comment]
Thanks. Looks good.

**Comment by Itsmemukesh** [comment]
Pushed to production: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-power-iaas-faqs#configuring
