### ISSUE TITLE
Additional custom image and import page fix ups 

### ISSUE THREAD

**Issue by smatzek** [ibm-cloud-docs/power-iaas#9]
After the field help fixes under #8, there are a few more import/custom image updates that should be done.

**Item 1**
The changes under #8 have resulted in a duplicate row in the field help on:
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-deploy-custom-image#upload-custom-boot

The field help row "Cloud Object Storage bucket name" should be removed as it is a duplicate of "Bucket Name" and "Bucket Name" is the current field name.

**Item 2**
The Region field help on 
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-deploy-custom-image#upload-custom-boot
and
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-importing-boot-image

lists "us-east, us-south, eu-de, or eu-gb", and I suspect that this list is out of date I have other regions listed when I go to the import screen:

![image](https://user-images.githubusercontent.com/13350259/111822536-e35c5480-88b1-11eb-8533-ea16888e018b.png)

**Comment by mpudota907** [comment]
@smatzek Updated.
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-deploy-custom-image#upload-custom-boot
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-importing-boot-image

**Comment by prarredd** [comment]
Assuming there are no more comments, closing the issue.
