### ISSUE TITLE
please provide steps on how to get to Figure 1

### ISSUE THREAD

**Issue by bikasprice** [ibm-cloud-docs/power-iaas#9]
Can we please add the following steps on how to get to Figure 1

Sign into the Cloud Portal (https://cloud.ibm.com)
select menu icon at the top left - Resource List
Open Services, and select the Power resource to assign the subnet to
click Subnets in the left table of contents
and click New Subnet

**Comment by mpbagwel** [comment]
@bikasprice Hi there, could you provide a link to the relevant page? Would you like those steps included here?

https://cloud.ibm.com/docs/infrastructure/power-iaas?topic=power-iaas-configuring-subnet

**Comment by bikasprice** [comment]
Hi, yes.  Sorry - I thought the location was included when I selected Open Issue on the page
https://cloud.ibm.com/docs/infrastructure/power-iaas?topic=power-iaas-configuring-subnet

**Comment by mpbagwel** [comment]
Not a problem. I added a few more steps to that page.  If something was missed or more work is required, please reopen the issue.

https://cloud.ibm.com/docs/infrastructure/power-iaas?topic=power-iaas-configuring-subnet
