### ISSUE TITLE
Incorrect path to rmcrefreshMD

### ISSUE THREAD

**Issue by acolvig** [ibm-cloud-docs/power-iaas#90]
Item 3 
/opt/rsct/rmcrefreshMD -s ctrmc

should be 
/opt/rsct/bin/rmcrefreshMD -s ctrmc

**Comment by Itsmemukesh** [comment]
Thanks for the changes.
Revised docs and changes are now pushed to test: https://test.cloud.ibm.com/docs/power-iaas?topic=power-iaas-recommended-rsct-package

**Comment by Itsmemukesh** [comment]
Changes pushed to production: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-recommended-rsct-package
