### ISSUE TITLE
unable to access the link 

### ISSUE THREAD

**Issue by takasou777** [ibm-cloud-docs/power-iaas#91]
Hello,
I cannot access the link "[Standard Edition monthly pricing options](https://www.ibm.com/downloads/cas/US-ENUS219-288-CA/name/ENUS219-288.PDF)"

Please check it.

**Comment by Itsmemukesh** [comment]
Hi,
Thanks for the changes. Fixed broken link. 
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-ha-dr#ha-dr-ha-standard
