### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by changwoojung** [ibm-cloud-docs/power-iaas#92]
Broken link into : [Deploying Red Hat OpenShift Container Platform 4.x on IBM Power Systems Virtual Servers](https://developer.ibm.com/components/ibm-power/series/deploy-ocp-cloud-paks-power-virtual-server/?_gl=1*1tgjhya*_ga*ODUyMDc1OTk1LjE2OTIzOTIzOTQ.*_ga_FYECCCS21D*MTY5MjQ5Mjg4My40LjEuMTY5MjQ5Mjg5MS4wLjAuMA..)

at https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-about-virtual-server#support-redhat-openshift

**Comment by Itsmemukesh** [comment]
The broken link is now fixed: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-about-virtual-server#support-redhat-openshift
