### ISSUE TITLE
Incorrect or broken link

### ISSUE THREAD

**Issue by changwoojung** [ibm-cloud-docs/power-iaas#93]
If you'd like to compare your current environment's performance to what's available through the Power Systems Virtual Server, see the [IBM Power Systems performance report](https://www.ibm.com/downloads/cas/K90RQOW8?_gl=1*164emvs*_ga*ODUyMDc1OTk1LjE2OTIzOTIzOTQ.*_ga_FYECCCS21D*MTY5MjQ5Mjg4My40LjEuMTY5MjQ5MzE2OS4wLjAuMA..). For a more condensed comparison, see [IBM Power Systems CPW performance data comparison](https://www.itechsol.com/wp-content/uploads/2018/07/IBM-Power-Systems-CPW-Performance-Data-Comparison-P7-vs-P8-vs-P9-rev3-July-2018.pdf).

[IBM Power Systems CPW performance data comparison](https://www.itechsol.com/wp-content/uploads/2018/07/IBM-Power-Systems-CPW-Performance-Data-Comparison-P7-vs-P8-vs-P9-rev3-July-2018.pdf). is not existing.

**Comment by Itsmemukesh** [comment]
Remove the last redundant sentence.
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-about-virtual-server#hardware-specifications
