### ISSUE TITLE
incorrect link

### ISSUE THREAD

**Issue by changwoojung** [ibm-cloud-docs/power-iaas#94]
[IBM Power System S1022 (9105-22A)](https://www.ibm.com/downloads/cas/MMOYB4YL?_gl=1*16tkqyw*_ga*ODUyMDc1OTk1LjE2OTIzOTIzOTQ.*_ga_FYECCCS21D*MTY5MjQ5Mjg4My40LjEuMTY5MjQ5MzU3NC4wLjAuMA..)

at https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-about-virtual-server#data-sheets

it points to E1080 datasheet.

**Comment by Itsmemukesh** [comment]
Hi,
This somehow got leaked to production and is currently a work in progress. I will remove it from production.
