### ISSUE TITLE
Consistency on the name of data center

### ISSUE THREAD

**Issue by changwoojung** [ibm-cloud-docs/power-iaas#95]
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-power-virtual-server#creating-service

In the IBM Cloud Console/create Power Systems Virtual Server workspace menu, Frankfurt 1 and Frankfurt 2 are shown - not FRA04, FRA05

**Comment by Itsmemukesh** [comment]
This is an old issue with no action taken. There is now a new topic available that describes the PowerVS regions.
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-ibm-cloud-reg
