### ISSUE TITLE
No document for Linux in PowerVS Backup strategy site

### ISSUE THREAD

**Issue by tyoshio-jp** [ibm-cloud-docs/power-iaas#97]
In "Backup strategies for IBM Power Systems Virtual Servers" (https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-backup-strategies), there are information for AIX and IBM i, but there is no info for Linux. There are customers using Linux on PowerVS, and documents for Linux is a must for these customers.
One specific requirement is that cloud-init has to be installed and enabled when capturing VM image, which is described in the document of PowerVC for Private Cloud (https://www.ibm.com/docs/en/powervc-cloud/2.1.1?topic=linux-installing-configuring-cloud-init-rhel). RHEL should be a priority as it is a strategic Linux distribution for IBM.

**Comment by Itsmemukesh** [comment]
Here is the doc page that talks about backing up the Linux instances - https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-backup-strategies#baas
User defined scripts/cloud-init info can be found here - https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-set-full-Linux#cloud-init-fls
