### ISSUE TITLE
 https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-VPN-connections#vpc-vpn

### ISSUE THREAD

**Issue by austinmama** [ibm-cloud-docs/power-iaas#98]
This content is incomplete and incorrect. The "VPN for VPC" information needs to be updated, arch diagrams described, and procedural steps require links to how this is done.  

The introduction is specific to the VPN that is deprecated and we should not be promoting the existing Power VPN, regardless if it is still in service until 2025.

**Comment by Itsmemukesh** [comment]
This issue is tracked through: https://github.ibm.com/cloud-docs/power-iaas/issues/372
Closing this one.
