### ISSUE TITLE
It looks like Flexible IOPS are also available in TOK04 and FRA05, but they are not listed in the docs.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/power-iaas#99]
Hello,
It looks like Flexible IOPS are also available in TOK04 and FRA05, but they are not listed in the docs.

https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-about-virtual-server#storage-tiers
>Flexible IOPS is currently available in DAL10, FRA04, LON04, MAD02, MON01, SYD04, SYD05, OSA21, and WDC07 data centers.

Best regards,

**Comment by Itsmemukesh** [comment]
DCs updated.
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-about-virtual-server#storage-tiers
